### PR TITLE
Revert changes to firefox tests

### PR DESCRIPTION
**Pull request by PatrykSzwer**
For #227

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
There is one test fail after this change:
image 
It's related to this: https://github.com/Starcounter/KitchenSink/pull/216#issuecomment-356313474
Now the question is, what should we do about it? @alshakero wasn't sure if he should fix this right now. @warpech WDYT?

**Comment by warpech** [comment]
If I understand correctly, the failing test expects Palindrom 3.1.0, but Starcounter 2.3.1 comes with Palindrom 3.0.9.

In my opinion the failing test should be removed or commented out in KitchenSink, because it won't pass in Starcounter 2.3.1.

**Comment by PatrykSzwer** [comment]
So since 2.3.1 was released we can't do any quick fixes to it? And if I understood @alshakero correctly before, It's not only tests problem, entire functionality stopped working.

**Comment by warpech** [comment]
> So since 2.3.1 was released we can't do any quick fixes to it? And if I understood @alshakero correctly before, It's not only tests problem, entire functionality stopped working.

The functionality did not *stop working*. It never worked in Starcounter 2.3.1.

We can do hotfixes to Starcounter 2.3.1, but the discussed functionality is a new feature. New features should not be added to old releases as hotfixes.

**Comment by PatrykSzwer** [comment]
Since tests passed I'll merge this, to have this change in kitchensink release. If you will have any comments please create new issue for that as a post-review.

**Pull request merged**
