### PR TITLE
updated puppet-redirect url attribute

### PR DESCRIPTION
**Pull request by PatrykSzwer**
Related to https://github.com/Palindrom/palindrom-redirect/issues/1

### CODE REVIEW

**Comment by Mihaiii** [comment]
Please don't merge this one yet.

**Comment by PatrykSzwer** [comment]
I've replaced puppet-redirect with palindrom-redirect here, please check if everything is ok.

**Comment by Mihaiii** [comment]
Everything is ok.

**Comment by PatrykSzwer** [comment]
For some reason tests for redirect are failing on teamcity, but locally everything is okey. I'll check that.

**Comment by PatrykSzwer** [comment]
Nvm, I've just run build on newest version of SC and everything is ok. Merging.

**Pull request merged**
