### PR TITLE
Problem 235: changing targetFramework to 4.6.1 for both projects in solution

### PR DESCRIPTION
**Pull request by kegor**
Possible fix for #235.

Changes in packages.json were made by manual changing targetFramework version for packages.

### CODE REVIEW

**Comment by warpech** [comment]
Weren't we supposed to use 4.6.1 in the apps? (https://github.com/Starcounter/Home/issues/347)

**Comment by PatrykSzwer** [comment]
TBH I don't see a reason why It shouldn't work with 4.6.2. 
But from the other side, It would be better if We had all apps in same versions. @kegor could You try to make it 4.6.1, not 4.6.2?

**Comment by kegor** [comment]
Hm, I tried to rerun check for 2.4 in TC and on a second time it was successful: https://teamcity.starcounter.org/viewLog.html?buildId=44094&, is this ok case for checking such situations?

**Comment by warpech** [comment]
It is not a matter if it won't work with 4.6.2. The matter is that 4.6.1 comes with VS2017 by default, as far as I understand.

**Comment by warpech** [comment]
> Hm, I tried to rerun check for 2.4 in TC and on a second time it was successful: https://teamcity.starcounter.org/viewLog.html?buildId=44094&, is this ok case for checking such situations?

Yes, as long as the tests are flaky, it is OK to re-run the test until it passes. Let's fix the flaky tests separately from this issue.

**Comment by warpech** [comment]
I can see that I have agreed to that myself in https://github.com/Starcounter/KitchenSink/issues/235#issuecomment-358638362, so I have no further comments :)

**Pull request merged**
