### PR TITLE
Fix teamcity tests

### PR DESCRIPTION
**Pull request by warpech**
Finally, I think I have fixed the TeamCity flaky tests (#181).

### CODE REVIEW

**Comment by warpech** [comment]
I will squash and merge this. What can go wrong?

**Comment by warpech** [comment]
@un-tone and @PatrykSzwer still, pls review this when back from vacation.

**Comment by un-tone** [comment]
So the solution in [this line](https://github.com/Starcounter/KitchenSink/pull/189/files#diff-4556d20ff9b33a014a25690691f407c7R54):
```csharp
Driver.Manage().Window.Maximize();
```
👍 Good to know about such unobvious things which can break tests.

**Comment by PatrykSzwer** [comment]
There is actually one thing that makes me suspicious. Tests were running in maximized windows already. See here: https://github.com/Starcounter/KitchenSink/blob/develop/test/KitchenSink.Tests/Utilities/WebDriverManager.cs#L36

But since this actually fixed our issue maybe there was something wrong in using this function there. I thing we should remove this line and check if It will break something.

**Comment by warpech** [comment]
Wow, that's interesting!

https://github.com/Starcounter/KitchenSink/blob/831c02c6a20f6a404b4a9e0419c296690df2c840/test/KitchenSink.Tests/Utilities/WebDriverManager.cs#L36 seems to really not work in Firefox, because the screenshots made in falling tests by Selenium were 100x200 pixels, not more. 

Maybe this is related to https://github.com/mozilla/geckodriver/issues/900 or one of the issues linked to it.

**Comment by warpech** [comment]
The bottom line is that in FF 55, `Maximize()` toggles the window size instead of maximizing it. Maybe we should stop using `Maximize()` and use this instead:

```
Driver.Manage().Window.SetPosition(new Point(0,0));
Driver.Manage().Window.SetSize(new Dimension(1024,768));
```

**Comment by PatrykSzwer** [comment]
Maybe way of implementing this matters for gecko. In line that I referenced Maximize is used on instance like this:
`IWebDriver eventDriver = new KitchenSinkTestEventListener(driver);`
When, In Your solution, maximize is called directly on Driver class. 
I'm not sure if this really makes a difference, just guessing, according to that previous solution didn't work and this does.

**Comment by warpech** [comment]
Let's continue the discussion in https://github.com/Starcounter/KitchenSink/issues/190

**Pull request merged**
