### PR TITLE
Fix pagination (next+prev buttons)

### LINKED ISSUE #248: Clicking next page in pagination advances two pages not one
##### Browsers affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

### PR DESCRIPTION
**Pull request by alshakero**
Fix #248

### CODE REVIEW

**Comment by tomalec** [comment]
Have you tried otherwise, to remove https://github.com/Starcounter/KitchenSink/pull/277/files#diff-515dd804e01781397feba2f69f2b2d37R41 and leave just polymer biding? You know less code => the better. As we aim for super-easy

**Comment by alshakero** [comment]
With all honesty I'm surprised it works now. But it does and it's clean.

**Comment by alshakero** [comment]
This is a side effect of using `spans` instead of `buttons`. See https://github.com/Starcounter/KitchenSink/issues/263.

**Comment by PatrykSzwer** [comment]
Ok, then I think It's ready to be merged.

**Pull request merged**
