### PR TITLE
Update Async package

### PR DESCRIPTION
**Pull request by PatrykSzwer**
For #300

### CODE REVIEW

**Comment by alshakero** [comment]
Can you please add tests for Async pages? Tests were passing even though those pages were broken.

**Comment by PatrykSzwer** [comment]
Good idea, I'll handle that!

**Comment by PatrykSzwer** [comment]
I added test for ProgressBar page that will fail if async library will stop working again. @alshakero please take a look.

**Comment by PatrykSzwer** [comment]
Build succeed, merging. Thank you!

**Pull request merged**
