### PR TITLE
Problem #269: fix for flaky DatepickerPage_SelectDate test.

### PR DESCRIPTION
**Pull request by kegor**
**Problem #269:**
image

**Solution:**
To avoid flaky behaviour `Asserts`'s were replaced on `WaitUntil`'s statements.

### CODE REVIEW

**Comment by kegor** [comment]
Actually, I see two approaches here:
1. Fixing next flaky tests when they will appear in TC.
2. Replacing all `Asserts` on `WaitUntil` in appropriate cases.
@warpech, @un-tone wdyt?

**Comment by un-tone** [comment]
If we can't confidently rely on `Assert`s in Selenium tests we should use `WaitUntil` in all such places where we do checking UI elements after some action.

**Comment by un-tone** [comment]
Otherwise, there always will appear flaky failed tests, here and there.

**Comment by warpech** [comment]
My problem with `WaitUntil` is that, as opposed to `Assert`, it gives very unclear error messages, such as:

```
OpenQA.Selenium.WebDriverTimeoutException : Timed out after 10 seconds
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at BlendingEditor.Tests.Ui.BasePage.WaitForElementToBeClickable(IWebElement elementName, Int32 seconds) in C:\TeamCity\BuildAgent\work\1ee82139cef36e7f\Blending\test\BlendingEditor.Tests\Ui\BasePage.cs:line 21
   at BlendingEditor.Tests.Ui.BasePage.ClickOn(IWebElement elementName, Int32 seconds) in C:\TeamCity\BuildAgent\work\1ee82139cef36e7f\Blending\test\BlendingEditor.Tests\Ui\BasePage.cs:line 26
   at BlendingEditor.Tests.Ui.LayoutGroupsPage.ClickButtonCreateLayout(IWebElement button) in C:\TeamCity\BuildAgent\work\1ee82139cef36e7f\Blending\test\BlendingEditor.Tests\Ui\LayoutGroupsPage.cs:line 125
   at BlendingEditor.Tests.Test.LayoutGroupsPageTest.LayoutGroupsPage_AddLayout() in C:\TeamCity\BuildAgent\work\1ee82139cef36e7f\Blending\test\BlendingEditor.Tests\Test\LayoutGroupsPageTest.cs:line 76
```

Any idea how to improve that? [This thread](https://stackoverflow.com/questions/10814807/how-to-improve-error-message-for-webdriver-expectedcondition) suggests two solutions:

1. generic helper method that uses `try`/`catch`
2. `withMessage` method from Selenium API

**Comment by kegor** [comment]
@warpech, If we decide to use common checks in tests (like title text check), then the first option looks more suitable, if we choose the second option, we will have to describe the same text in each test that checks the title, right?

@un-tone wdyt?

**Comment by kegor** [comment]
Hi @warpech, what do you think, do you agree with @un-tone?

**Pull request merged**
