### PR TITLE
Removed unnecessary maximize call

### PR DESCRIPTION
**Pull request by PatrykSzwer**
for #190

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
I've run tests 4 times and seems like my last change fixed our problem. Please check by yourself.

**Comment by PatrykSzwer** [comment]
I've came to some interesting results.
Seems like, what is failing our tests in firefox is... maximizing itself! When I changed way of maximizing to argument in options, I though everything is working, but turns out that Firefox doesn't have argument for maximizing. What really happen is that firefox had maximizing turned off completely. And THAT fixed tests. 
Now there is a question. Should we completely shut down maximization in firefox? Seems like It's not needed for tests to be run properly.

**Comment by warpech** [comment]
If maximization is not needed, then why remove it only from Firefox? It should be consistently removed from all drivers.

**Comment by PatrykSzwer** [comment]
Please check if tests passes locally for you, because I have some flacky ones, but on teamcity everything seems fine.

**Comment by warpech** [comment]
Tests locally pass but I get a lot of TearDown errors:



Do you also get these?

**Comment by PatrykSzwer** [comment]
Yes I've started getting those also couple days ago. I though It can be related to some update or something, even Resharper is also showing them with red color but not categorizing as failed tests. But I've just looked into it further and found out that It's caused by getting snaphsot in teardown method. I'll fix it right away.

**Pull request merged**
