### PR TITLE
Add guidelines for the project

### PR DESCRIPTION
**Pull request by warpech**
@Starcounter/webplatformteam can you please review if you agree with the guidelines and the wording?

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
Seems ok to me. I would maybe even bold/color or in some other way mark importance of sentence:
`It is recommended to follow these guidelines for Starcounter apps in general.`

**Comment by tomalec** [comment]
Could you just clarify why would you limit light dom to native elements only:
```md
- ✔️ Only use native HTML without classes in the light DOM. Style them in Shadow DOM.
...
- ✔️ Minimize the client side logic. For interactivity use external custom elements installed via Bower.
```

I think our guideline is rather:
- Use elements without classes in light dom,
- Do not put style-related div-soup in light dom,
- Use **simplest building blocks** in light dom,
- Use layout related div-soup, classes, or custom elements in Shadow DOM

I could imagine plenty of custom elements that fits great in light dom: `<palindrom-redirect>`, `<platinum-bluetooth>`, `<vaadin-parrot name="Fiesta Parrot">`, and so on.

**Comment by warpech** [comment]
> Could you just clarify why would you limit light dom to native elements

I don't mean use "native elements". I mean exactly what you wrote in bullet points.

Is it clearer now?

**Comment by warpech** [comment]
Assuming yes. Please open a new issue otherwise

**Pull request merged**
